image:
  file: .gitpod.Dockerfile

tasks:
  - init: cd cloud && npm install && cd ..
  - command: cd cloud && parse-server --appId $APPLICATION_ID --clientKey $CLIENT_KEY --masterKey $MASTER_KEY --databaseURI mongodb://localhost/test && cd ..
    name: Run Parse Server
