image:
  file: .gitpod.Dockerfile

tasks:
  - name: Run Parse Server
    init: cd cloud && npm install && cd ..
    command: parse-server --appId $APPLICATION_ID --clientKey $CLIENT_KEY --masterKey $MASTER_KEY --databaseURI mongodb://localhost/test --allowClientClassCreation=false --allowExpiredAuthDataToken=false
