-- MySQL Script generated by MySQL Workbench
-- Sat Apr 22 10:17:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bancodadosapi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancodadosapi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancodadosapi` DEFAULT CHARACTER SET utf8 ;
USE `bancodadosapi` ;

-- -----------------------------------------------------
-- Table `bancodadosapi`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodadosapi`.`login` (
  `idLinkedIn` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NULL,
  `foto` VARCHAR(150) NULL,
  PRIMARY KEY (`idLinkedIn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancodadosapi`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodadosapi`.`endereco` (
  `cep` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`cep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancodadosapi`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodadosapi`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NOT NULL,
  `tipoConta` VARCHAR(45) NULL,
  `dataNascimento` DATETIME NULL,
  `numeroEndereco` VARCHAR(45) NULL,
  `complementoEndereco` VARCHAR(45) NULL,
  `dddFixo` VARCHAR(45) NULL,
  `numeroFixo` VARCHAR(45) NULL,
  `dddCelular` VARCHAR(45) NULL,
  `numeroCelular` VARCHAR(45) NULL,
  `login_idLinkedIn` INT NOT NULL,
  `endereco_cep` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `login_idLinkedIn`),
  INDEX `fk_usuario_login1_idx` (`login_idLinkedIn` ASC) VISIBLE,
  INDEX `fk_usuario_endereco1_idx` (`endereco_cep` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_login1`
    FOREIGN KEY (`login_idLinkedIn`)
    REFERENCES `bancodadosapi`.`login` (`idLinkedIn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_endereco1`
    FOREIGN KEY (`endereco_cep`)
    REFERENCES `bancodadosapi`.`endereco` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancodadosapi`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodadosapi`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `razaoSocial` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `dddComercial` VARCHAR(45) NULL,
  `numeroComercial` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  `endereco_cep` INT NOT NULL,
  PRIMARY KEY (`idempresa`),
  INDEX `fk_empresa_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_empresa_endereco1_idx` (`endereco_cep` ASC) VISIBLE,
  CONSTRAINT `fk_empresa_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bancodadosapi`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_endereco1`
    FOREIGN KEY (`endereco_cep`)
    REFERENCES `bancodadosapi`.`endereco` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancodadosapi`.`vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodadosapi`.`vaga` (
  `idvaga` INT NOT NULL AUTO_INCREMENT,
  `cbo` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `tipoContratacao` VARCHAR(45) NOT NULL,
  `tipoVaga` VARCHAR(45) NOT NULL,
  `salario` VARCHAR(45) NOT NULL,
  `beneficios` VARCHAR(45) NULL,
  `tecnologiaPrincipal` VARCHAR(45) NOT NULL,
  `tecnologiaDesejados` VARCHAR(45) NULL,
  `empresa_idempresa` INT NOT NULL,
  PRIMARY KEY (`idvaga`),
  INDEX `fk_vaga_empresa1_idx` (`empresa_idempresa` ASC) VISIBLE,
  CONSTRAINT `fk_vaga_empresa1`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `bancodadosapi`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancodadosapi`.`curriculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodadosapi`.`curriculo` (
  `idcurriculo` INT NOT NULL AUTO_INCREMENT,
  `pdf` BLOB NOT NULL,
  `tecnologiaPrincipal` VARCHAR(45) NULL,
  `tempoExperienciaTecnologiaPrincipal` VARCHAR(45) NULL,
  `tecnologiaOpcional` VARCHAR(45) NULL,
  `tempoExperienciaTecnologiaOpcional` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idcurriculo`),
  INDEX `fk_curriculo_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_curriculo_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bancodadosapi`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
