-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 12:16:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE,
  SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema bancodadosapi
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bancodadosapi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancodadosapi` DEFAULT CHARACTER SET utf8;
USE `bancodadosapi`;
-- -----------------------------------------------------
-- Table `bancodadosapi`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodadosapi`.`login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `idLinkedIn` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLogin`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `bancodadosapi`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(8) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `logradouro` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cep_numero` (`cep`, `numero`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `bancodadosapi`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodadosapi`.`telefone` (
  `idtelefone` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `ddd` VARCHAR(45) NULL,
  `numero` VARCHAR(9) NULL,
  PRIMARY KEY (`idtelefone`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `bancodadosapi`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS bancodadosapi.usuario (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(150) NULL,
  `tipoConta` VARCHAR(45) NULL,
  `dataNascimento` DATETIME NULL,
  `login_idLogin` INT NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  `telefone_idtelefone` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_login1_idx` (`login_idLogin` ASC) VISIBLE,
  INDEX `fk_usuario_endereco1_idx` (`endereco_idendereco` ASC) VISIBLE,
  INDEX `fk_usuario_telefone1_idx` (`telefone_idtelefone` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_login1` FOREIGN KEY (`login_idLogin`) REFERENCES bancodadosapi.login (`idLogin`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_endereco1` FOREIGN KEY (`endereco_idendereco`) REFERENCES bancodadosapi.endereco (`idendereco`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_telefone1` FOREIGN KEY (`telefone_idtelefone`) REFERENCES bancodadosapi.telefone (`idtelefone`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `bancodadosapi`.`vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodadosapi`.`vaga` (
  `idvaga` INT NOT NULL AUTO_INCREMENT,
  `cbo` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `tipoContratacao` VARCHAR(45) NOT NULL,
  `tipoVaga` VARCHAR(45) NOT NULL,
  `salario` VARCHAR(45) NOT NULL,
  `beneficios` VARCHAR(45) NULL,
  `tecnologiaPrincipal` VARCHAR(45) NOT NULL,
  `tecnologiaDesejados` VARCHAR(45) NULL,
  PRIMARY KEY (`idvaga`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `bancodadosapi`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodadosapi`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `razaoSocial` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `vaga_idvaga` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  `telefone_idtelefone` INT NOT NULL,
  PRIMARY KEY (`idempresa`),
  INDEX `fk_empresa_vaga1_idx` (`vaga_idvaga` ASC) VISIBLE,
  INDEX `fk_empresa_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_empresa_endereco1_idx` (`endereco_idendereco` ASC) VISIBLE,
  INDEX `fk_empresa_telefone1_idx` (`telefone_idtelefone` ASC) VISIBLE,
  CONSTRAINT `fk_empresa_vaga1` FOREIGN KEY (`vaga_idvaga`) REFERENCES `bancodadosapi`.`vaga` (`idvaga`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_usuario1` FOREIGN KEY (`usuario_idusuario`) REFERENCES `bancodadosapi`.`usuario` (`idusuario`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_endereco1` FOREIGN KEY (`endereco_idendereco`) REFERENCES `bancodadosapi`.`endereco` (`idendereco`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_telefone1` FOREIGN KEY (`telefone_idtelefone`) REFERENCES `bancodadosapi`.`telefone` (`idtelefone`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `bancodadosapi`.`curriculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodadosapi`.`curriculo` (
  `idcurriculo` INT NOT NULL AUTO_INCREMENT,
  `pdf` BLOB NOT NULL,
  `tecnologiaPrincipal` VARCHAR(45) NULL,
  `tempoExperienciaTecnologiaPrincipal` VARCHAR(45) NULL,
  `tecnologiaOpcional` VARCHAR(45) NULL,
  `tempoExperienciaTecnologiaOpcional` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idcurriculo`),
  INDEX `fk_curriculo_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_curriculo_usuario1` FOREIGN KEY (`usuario_idusuario`) REFERENCES `bancodadosapi`.`usuario` (`idusuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;